package gtfs

import (
	"testing"
	"time"
)

// FR1 — Golden end-to-end behaviour lock.
//
// This test runs the FULL production pipeline against the committed real
// fixtures and pins its observable output exactly:
//
//	gtfs_static.zip  ->  StaticDB
//	tripupdates.gtfsr -> Poller.parse (LiveStore overlay)
//	QueryArrivals(now = fixtureNow())  ->  []Arrival
//
// The expected tables below were generated by running the pipeline once and
// capturing the actual output verbatim. They are the behaviour lock: any change
// to observable arrivals — route, headsign, scheduled time, whether realtime is
// applied, the delay, or the added flag, in this exact order — fails this test.
// That is precisely what makes an internal refactor (or a performance
// optimisation) safe: if QueryArrivals/parse/buildFromZIPFile still produce
// these arrivals, behaviour is provably unchanged; if they don't, the diff is
// caught here instead of silently shipping to the device.
//
// Everything is deterministic: `now` is pinned to fixtureNow() (the feed's own
// header timestamp, in Europe/Dublin) and the LiveStore clock is pinned via
// withClock, so captured delays/ETAs map to fixed values. To intentionally
// re-baseline (only when behaviour is *meant* to change), re-run the dump logic
// and paste the new tables.

// goldenArrival is the observable projection of an Arrival that this behaviour
// lock pins. ScheduledRel is the scheduled time formatted in Europe/Dublin as
// "15:04"; HasRealtime records whether RealtimeTime was set (a non-zero overlay
// from the realtime feed) without pinning the volatile absolute timestamp.
type goldenArrival struct {
	RouteShort   string
	Headsign     string
	Scheduled    string // "15:04" in Europe/Dublin
	HasRealtime  bool
	DelayMinutes int
	IsAdded      bool
}

// goldenWant is the exact, ordered expectation per fixture stop. Captured from a
// real TFI static feed (trimmed to 3 stops) overlaid with a real GTFS-RT capture
// at the canonical instant 2026-06-26 19:06:25 +01 (Europe/Dublin).
var goldenWant = map[string][]goldenArrival{
	"478": {
		{RouteShort: "4", Headsign: "Heuston Station", Scheduled: "19:05", HasRealtime: true, DelayMinutes: 1, IsAdded: false},
		{RouteShort: "4", Headsign: "Heuston Station", Scheduled: "19:17", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "7A", Headsign: "Mountjoy Square", Scheduled: "19:14", HasRealtime: true, DelayMinutes: 5, IsAdded: false},
		{RouteShort: "4", Headsign: "Heuston Station", Scheduled: "19:37", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "7A", Headsign: "Mountjoy Square", Scheduled: "19:44", HasRealtime: true, DelayMinutes: 1, IsAdded: false},
		{RouteShort: "4", Headsign: "Heuston Station", Scheduled: "19:57", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "7A", Headsign: "Mountjoy Square", Scheduled: "20:14", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "4", Headsign: "Heuston Station", Scheduled: "20:17", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "7", Headsign: "Mountjoy Square", Scheduled: "20:23", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
	},
	"2808": {
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "19:08", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "19:23", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "19:38", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "19:53", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "20:08", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "20:23", HasRealtime: false, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "S2", Headsign: "Heuston Station", Scheduled: "20:36", HasRealtime: false, DelayMinutes: 0, IsAdded: false},
	},
	"999126": {
		{RouteShort: "DART", Headsign: "Greystones", Scheduled: "19:06", HasRealtime: true, DelayMinutes: 6, IsAdded: false},
		{RouteShort: "DART", Headsign: "Bray (Daly)", Scheduled: "19:15", HasRealtime: true, DelayMinutes: 3, IsAdded: false},
		{RouteShort: "DART", Headsign: "Bray (Daly)", Scheduled: "19:25", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Howth", Scheduled: "19:26", HasRealtime: true, DelayMinutes: 4, IsAdded: false},
		{RouteShort: "DART", Headsign: "Greystones", Scheduled: "19:35", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Bray (Daly)", Scheduled: "19:45", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Howth", Scheduled: "19:43", HasRealtime: true, DelayMinutes: 5, IsAdded: false},
		{RouteShort: "DART", Headsign: "Dublin Connolly", Scheduled: "19:56", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Bray (Daly)", Scheduled: "19:59", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Howth", Scheduled: "20:06", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Malahide", Scheduled: "20:13", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Greystones", Scheduled: "20:15", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
		{RouteShort: "DART", Headsign: "Bray (Daly)", Scheduled: "20:26", HasRealtime: true, DelayMinutes: 0, IsAdded: false},
	},
}

// TestGolden_Pipeline locks the end-to-end pipeline output (see file header).
func TestGolden_Pipeline(t *testing.T) {
	loc, err := time.LoadLocation("Europe/Dublin")
	if err != nil {
		t.Fatalf("load Europe/Dublin: %v", err)
	}

	// Build the full pipeline exactly as production does.
	db := loadFixtureDB(t)
	poller := NewPoller("", "", NewDB(db))
	withClock(poller.Store(), fixtureNow()) // deterministic LiveStore clock
	if err := poller.parse(loadFixtureFeed(t)); err != nil {
		t.Fatalf("parse realtime fixture: %v", err)
	}

	now := fixtureNow()
	for _, stop := range fixtureStops() {
		want := goldenWant[stop]
		got := QueryArrivals(db, poller.Store(), stop, now, 90, 0, nil)

		if len(got) != len(want) {
			t.Errorf("stop %s: got %d arrivals, want %d", stop, len(got), len(want))
			// Dump the actual rows to make re-baselining easy on a real change.
			for i, a := range got {
				t.Logf("  got[%d] = {RouteShort: %q, Headsign: %q, Scheduled: %q, HasRealtime: %v, DelayMinutes: %d, IsAdded: %v}",
					i, a.RouteShort, a.Headsign, a.ScheduledTime.In(loc).Format("15:04"),
					!a.RealtimeTime.IsZero(), a.DelayMinutes, a.IsAdded)
			}
			continue
		}

		for i, a := range got {
			g := goldenArrival{
				RouteShort:   a.RouteShort,
				Headsign:     a.Headsign,
				Scheduled:    a.ScheduledTime.In(loc).Format("15:04"),
				HasRealtime:  !a.RealtimeTime.IsZero(),
				DelayMinutes: a.DelayMinutes,
				IsAdded:      a.IsAdded,
			}
			if g != want[i] {
				t.Errorf("stop %s arrival[%d]:\n  got  %+v\n  want %+v", stop, i, g, want[i])
			}
		}
	}
}
